### ISSUE TITLE
Board Model

### ISSUE THREAD

**Issue by abose** [TapanManu/CarromBoard#3]
- Board orientation
        1. Player 1  orientation
        2. Player 2 orientation
- Board dimensions
        1.Length
        2.Breadth
- Pockets
        1.radius
        2.rx,ry
-Side players owner
-Coins of each player
-Coins [num coins] {rx,ry,color}
         1.Queen(10,10,red)
         2.White (10,10,white)
         3.Black (10,10,black)
         4.Striker(15,15,green)
-Friction Coefficient 
         -Same for both floor and walls

**Comment by TapanManu** [comment]
holes ,walls are completed
Friction not added
